---
title: "TSA"
author: "Yuxiang Ren"
output: pdf_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
---
#packges    
```{r packages}
library(readxl)
#library(xlsx) #this package doesn't work on Macs very well
library(tidyr)
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)

library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
library(dplyr)

```

#data
```{r}
raw <- read.csv("./Data/Processed/PM2.5_daily_city_2000_2021.csv")

raw_wider <- raw %>% pivot_wider(names_from = city_id, values_from = meanpm)

```
#Beijing
##data
```{r}
Beijing_raw <- raw_wider[,c("year","month","day","1100")]

Beijing_clean <- Brijing_raw %>%
  mutate(date = ymd(paste(year, month, day, sep = "-"))) %>%
  select(-year, -month, -day) %>%
  rename(meanpm = `1100`)

beijing_train <- Beijing_clean %>% filter(date < as.Date("2021-01-01"))
beijing_test <- Beijing_clean %>% filter(date >= as.Date("2021-01-01"))

ts_beijing_train <- msts(beijing_train$meanpm, seasonal.periods =c(7,365.25),
                           start=c(2000,1,1))
```

##STL+ETS
have negative value
```{r STL+ETS 1}
ETS_Beijing <-  stlf(ts_beijing_train,h=365)
autoplot(ETS_Beijing) + ylab("Beijing")
autoplot(ts_beijing_train) +
  autolayer(ETS_Beijing, series="STL + ETS",PI=FALSE) +
  ylab("Beijing")

```

```{r STL+ETS log}
ts_beijing_log_train <- log(ts_beijing_train)
ETS_Beijing_log <- stlf(ts_beijing_log_train, h=365)
ETS_Beijing_logexp <- exp(ETS_Beijing_log$mean)
autoplot(ts_beijing_train) +
  autolayer(ETS_Beijing_logexp, series="STL + ETS",PI=FALSE) +
  ylab("Beijing")

```

##ARIMA + FOURIER terms
```{r}
ARIMA_Four_Beijing <- auto.arima(ts_beijing_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_beijing_train, 
                                          K=c(2,12)))

AF_for_Beijing <- forecast(ARIMA_Four_Beijing,
                           xreg=fourier(ts_beijing_train,
                                        K=c(2,12),
                                        h=365),
                           h=365
                           ) 
autoplot(ts_beijing_train) +
  autolayer(AF_for_Beijing, series="ARIMA_FOURIER",PI=FALSE) +
  ylab("PM2.5")


```

